spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: neha@12345
    url: jdbc:mysql://localhost:3306/user_registration
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
