spring:
  profile :
    active : qa
management:
  endpoints:
    web:
      exposure:
        include: "*"


---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: neha@12345
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to the world

---
spring:
  profiles : qa

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: neha@12345
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: Welcome to the world
---
spring:
  profiles : prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: neha@12345
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to the world
